### ISSUE TITLE
On sharing copyrighted content

### ISSUE THREAD

**Issue by Aspie96** [revoltchat/legal#5]
I am not a lawyer and this is not legal advice.

> Sharing any kind of copyrighted content, or any type of content that violates another person's personal, intellectual property or other rights. This includes any content that would violate the Digital Millennium Copyright Act (DMCA).

I understand and agree with the intention of this, however the wording can be improved.

The issue is "[s]haring any kind of copyrighted content". There are three cases in which this is legal and should be allowed:
- The person sharing it is the copyright holder (which is true for any significant portion of original enough text).
- The person sharing it has been authorized by a copyright holder.
- In that specific case, sharing that content falls under an exception to copyright.

Even in these three cases, one is technically sharing copyrighted content, so is in violation of the literal meaning (not the intention) of the first phrase of this clause and, since the rest is in disjunction, of the clause as a whole.

I believe the clause should be rephrased such that its literal meaning aligns with its intention.

**Comment by Rexogamer** [comment]
I am also not a lawyer, but I think something like this might be better at portraying the intended policy:
> *Sharing any kind of copyrighted content that you do not own without authorisation from the copyright holder...*

**Comment by Aspie96** [comment]
That is a much better content, but you're leaving out the case of copyright exceptions, which also don't constitute copyright infringment.

A bruteforce way of solving this would be to replace "Sharing any kind of copyrighted content" with "Copyright infringement":
> Copyright infringement, or sharing any type of content that violates another person's personal, intellectual property or other rights. This includes any content that would violate the Digital Millennium Copyright Act (DMCA).

Or include "copyright" in "intellectual property":
> Sharing any kind of content in violation of another person's personal, intellectual property (including copyright and related rights) or other rights. This includes any content that would violate the Digital Millennium Copyright Act (DMCA).

Or make it explicit:
> Sharing any kind of copyrighted content that you do not own without authorisation from the copyright holder (except when clearly allowed by applicable limitations or exceptions to copyright)...

I am not too happy about either of these three (I believe they all convey the message correctly, I just feel they could be more elegant), but I feel they would solve the issue.
